import { Providers } from '@/components/providers'
import './globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { fontMono, fontSans } from '@/lib/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          'font-sans antialiased',
          fontSans.variable,
          fontMono.variable
        )}>
      <Providers attribute="class" defaultTheme="system" enableSystem>
      <div className="flex flex-col min-h-screen">
      <main className="flex flex-col flex-1 bg-muted/50">{children}</main>
        </div>
        </Providers>
        </body>
    </html>
  )
}
